# Generated by Django 3.2 on 2021-04-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='victim_images')),
                ('name', models.CharField(max_length=255, verbose_name='Victim Name')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('occupation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Occupation')),
                ('social_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Social Status')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Victim',
                'verbose_name_plural': 'Victims',
                'ordering': ('-date_created',),
            },
        ),
    ]
