# Generated by Django 3.2 on 2021-04-28 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210428_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date_created',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_at',
            new_name='date_updated',
        ),
    ]
