# Generated by Django 3.2 on 2021-05-08 12:59

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='avatar/avatar-default.png', null=True, upload_to=accounts.models.image_storage_path, verbose_name='Profile Picture'),
        ),
    ]
