# Generated by Django 3.2 on 2021-05-01 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date_created',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ('-date_created',), 'verbose_name': 'Ordered Product', 'verbose_name_plural': 'Ordered Products'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-date_created', '-status', '-payment_id'), 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
